name: mobile_portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  import_sorter: ^4.6.0
  responsive_builder: ^0.4.2
  font_awesome_flutter: ^10.0.0
  provider: ^6.0.2
  flutter_switch: ^0.3.2
  animated_text_kit: ^4.2.1
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/apps/
    - images/works/
